name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile on Linux
      run: |
        gcc *.c -o main

    - name: Test on Linux
      run: |
        # Run tests here if applicable

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile on Windows
      run: |
        gcc *.c -o main.exe

    - name: Test on Windows
      run: |
        # Run tests here if applicable
