name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cpu-type: [x86, x64, amd]

    steps:
    - uses: actions/checkout@v4

    - name: Compile on Linux
      run: |
        gcc *.c -o main
        mkdir -p artifacts/linux
        mv main artifacts/linux/main

    - name: Test on Linux
      run: |
        # Run tests here if applicable

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-executables
        path: artifacts/linux

  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        cpu-type: [x86, x64, amd]

    steps:
    - uses: actions/checkout@v4

    - name: Compile on Windows
      run: |
        gcc *.c -o main.exe
        mkdir -p artifacts/windows
        mv main.exe artifacts/windows/main.exe

    - name: Test on Windows
      run: |
        # Run tests here if applicable

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-executables
        path: artifacts/windows

  build-macos:
    runs-on: macos-latest

    strategy:
      matrix:
        cpu-type: [x86, x64, amd]

    steps:
    - uses: actions/checkout@v4

    - name: Compile on macOS
      run: |
        gcc *.c -o main
        mkdir -p artifacts/macos
        mv main artifacts/macos/main

    - name: Test on macOS
      run: |
        # Run tests here if applicable

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-executables
        path: artifacts/macos
